import "dotenv/config";
import mongoose from "mongoose";
import Question from "../models/Question.js";

// --- POMOĆNE FUNKCIJE ---
const mcq = (text, options, correctAnswer, difficulty = "easy", grade = 5) => ({
  type: "mcq", text, options, correctAnswer, difficulty, grade,
});

const dragDrop = (text, items, zones, correctPairs, difficulty = "medium", grade = 6) => ({
  type: "drag_drop", text, difficulty, grade,
  specialData: { items, zones, correctPairs },
});

const mapClick = (text, mapCenter, zoom, choices, correctId, difficulty = "medium", grade = 6, markerSize = 6) => ({
  type: "map_click", text, difficulty, grade,
  specialData: { mapCenter, zoom, choices, correctId, markerSize },
});

// === SRBIJA ===
const srbija = [
  mcq("Glavni grad Srbije je:", ["Beograd", "Novi Sad", "Niš", "Kragujevac"], "Beograd", "easy", 5),
  mcq("Koje dve reke se sastaju u Beogradu?", ["Sava i Dunav", "Morava i Drina", "Tisa i Sava", "Nišava i Morava"], "Sava i Dunav", "easy", 5),
  mcq("Glavni grad Vojvodine je:", ["Novi Sad", "Subotica", "Zrenjanin", "Sombor"], "Novi Sad", "easy", 5),
  mcq("Srbija se nalazi na kontinentu:", ["Evropa", "Azija", "Afrika", "Australija"], "Evropa", "easy", 5),
  mcq("Koja reka protiče kroz Niš?", ["Nišava", "Drina", "Tisa", "Lepenica"], "Nišava", "easy", 5),
  mcq("Najveća reka koja protiče kroz Srbiju je:", ["Dunav", "Sava", "Morava", "Drina"], "Dunav", "easy", 5),
  mcq("Koji nacionalni park je poznat po planini i ski centru?", ["Kopaonik", "Tara", "Đerdap", "Fruška gora"], "Kopaonik", "easy", 5),
  mcq("Panonska nizija se nalazi uglavnom na:", ["Severu Srbije", "Jugu Srbije", "Zapadu Srbije", "Istoku Srbije"], "Severu Srbije", "easy", 5),
  mcq("Koja država se nalazi severno od Srbije?", ["Mađarska", "Grčka", "Albanija", "Crna Gora"], "Mađarska", "easy", 5),
  mcq("Koja država se nalazi istočno od Srbije?", ["Bugarska", "Italija", "Austrija", "Švajcarska"], "Bugarska", "easy", 5),
  mcq("Koja planina je poznata po turističkom centru Tornik?", ["Zlatibor", "Rtanj", "Fruška gora", "Jastrebac"], "Zlatibor", "easy", 5),
  mcq("Koji grad je sedište Šumadijskog okruga?", ["Kragujevac", "Valjevo", "Kraljevo", "Čačak"], "Kragujevac", "easy", 5),
  mcq("Koja reka protiče kroz Užice?", ["Đetinja", "Drina", "Morava", "Sava"], "Đetinja", "easy", 5),
  mcq("Koji grad je sedište Nišavskog okruga?", ["Niš", "Leskovac", "Pirot", "Vranje"], "Niš", "easy", 5),
  mcq("Koja reka protiče kroz Kraljevo?", ["Ibar", "Tisa", "Sava", "Morava"], "Ibar", "easy", 5),
  mcq("Koji grad je poznat po Petrovaradinskoj tvrđavi?", ["Novi Sad", "Subotica", "Zrenjanin", "Sombor"], "Novi Sad", "easy", 5),
  mcq("Koji grad se nalazi na Dunavu i poznat je po tvrđavi?", ["Golubac", "Požarevac", "Zaječar", "Kikinda"], "Golubac", "easy", 5),
  mcq("Koja reka čini deo granice Srbije i Hrvatske?", ["Dunav", "Morava", "Ibar", "Nišava"], "Dunav", "easy", 5),
  mcq("Koji grad je poznat po tvrđavi i nalazi se na Dunavu?", ["Smederevo", "Šabac", "Kikinda", "Vranje"], "Smederevo", "easy", 5),
  mcq("Koja planina je poznata po manastirima i nalazi se u Vojvodini?", ["Fruška gora", "Stara planina", "Kopaonik", "Golija"], "Fruška gora", "easy", 5),
  mcq("Koja je najveća prirodna oblast u severnom delu Srbije?", ["Vojvodina", "Šumadija", "Raška", "Metohija"], "Vojvodina", "easy", 5),
  mcq("Koji grad je drugi po veličini u Srbiji?", ["Novi Sad", "Niš", "Kragujevac", "Subotica"], "Novi Sad", "easy", 5),
  mcq("Koji grad se nalazi na obali Save?", ["Šabac", "Kikinda", "Zrenjanin", "Vranje"], "Šabac", "easy", 5),
  mcq("Koja planina se nalazi jugoistočno od Beograda i poznata je po tornju?", ["Avala", "Rtanj", "Fruška gora", "Kablar"], "Avala", "easy", 5),
  mcq("Koja planina je poznata po ski-centru Kopaonik?", ["Kopaonik", "Tara", "Zlatibor", "Stara planina"], "Kopaonik", "easy", 5),
  mcq("Na kojoj planini se nalazi vrh Midžor?", ["Stara planina", "Kopaonik", "Tara", "Zlatibor"], "Stara planina", "medium", 6),
  mcq("Koja planina se nalazi kod Čačka i poznata je po kanjonu?", ["Kablar", "Rtanj", "Jastrebac", "Besna Kobila"], "Kablar", "medium", 6),
  mcq("Koja reka nastaje spajanjem Južne i Zapadne Morave?", ["Velika Morava", "Dunav", "Sava", "Ibar"], "Velika Morava", "medium", 6),
  mcq("Koje jezero je prirodno i nalazi se na jugu Srbije?", ["Vlasinsko jezero", "Palićko jezero", "Borsko jezero", "Đerdapsko jezero"], "Vlasinsko jezero", "medium", 6),
  mcq("Koja planina je poznata po spomeniku i turističkom značaju?", ["Rtanj", "Zlatibor", "Tara", "Javor"], "Rtanj", "medium", 6),
  dragDrop("Poveži reku sa gradom kroz koji protiče.",
    [{ id: "nisava", label: "Nišava" }, { id: "ibar", label: "Ibar" }, { id: "djetinja", label: "Đetinja" }, { id: "sava", label: "Sava" }],
    [{ id: "nis", label: "Niš" }, { id: "kraljevo", label: "Kraljevo" }, { id: "uzice", label: "Užice" }, { id: "sabac", label: "Šabac" }],
    { nisava: "nis", ibar: "kraljevo", djetinja: "uzice", sava: "sabac" }, "medium", 6),
  mapClick("Klikni Beograd na mapi Srbije.", [20.9, 44.2], 7,
    [{ id: "beograd", coordinates: [20.4489, 44.7866] }, { id: "novi-sad", coordinates: [19.8335, 45.2671] }, { id: "nis", coordinates: [21.8958, 43.3209] }],
    "beograd", "medium", 5, 6),
  mapClick("Klikni Novi Sad na mapi Srbije.", [20.9, 44.2], 7,
    [{ id: "beograd", coordinates: [20.4489, 44.7866] }, { id: "novi-sad", coordinates: [19.8335, 45.2671] }, { id: "nis", coordinates: [21.8958, 43.3209] }],
    "novi-sad", "medium", 5, 6),
  mapClick("Klikni Niš na mapi Srbije.", [20.9, 44.2], 7,
    [{ id: "beograd", coordinates: [20.4489, 44.7866] }, { id: "novi-sad", coordinates: [19.8335, 45.2671] }, { id: "nis", coordinates: [21.8958, 43.3209] }],
    "nis", "medium", 5, 6),
  mcq("Koji grad je sedište Rasinskog okruga?", ["Kruševac", "Trstenik", "Aleksandrovac", "Brus"], "Kruševac", "medium", 8),
  mcq("Koji je najviši vrh u Srbiji (na Prokletijama)?", ["Velika Rudoka", "Midžor", "Pančićev vrh", "Trem"], "Velika Rudoka", "hard", 8),
  mcq("Sa kojom državom Srbija ima najdužu kopnenu granicu?", ["Rumunija", "Hrvatska", "Bugarska", "Mađarska"], "Rumunija", "medium", 8),
  mcq("Koja je najduža reka koja celim tokom protiče kroz Srbiju?", ["Zapadna Morava", "Velika Morava", "Južna Morava", "Ibar"], "Velika Morava", "medium", 8),
  mcq("Koji nacionalni park je poznat po najvećoj klisuri u Evropi?", ["Đerdap", "Tara", "Šar-planina", "Fruška gora"], "Đerdap", "easy", 8),
  mcq("Koji grad je centar Mačvanskog okruga?", ["Šabac", "Loznica", "Valjevo", "Kruševac"], "Šabac", "medium", 8),
  mcq("Koje je najveće veštačko jezero u Srbiji?", ["Đerdapsko jezero", "Vlasinsko jezero", "Perućac", "Gazivode"], "Đerdapsko jezero", "easy", 8),
  mcq("Koja planina u Srbiji je jedina vulkanskog porekla?", ["Crni vrh", "Rtanj", "Rudnik", "Golija"], "Rudnik", "hard", 8),
  mcq("Gde se nalazi najveći rudnik bakra u Srbiji?", ["Bor", "Majdanpek", "Kostolac", "Kolubara"], "Bor", "easy", 8),
  mcq("Koji grad u Srbiji je poznat kao 'srpski Mančester'?", ["Leskovac", "Vranje", "Pirot", "Zaječar"], "Leskovac", "medium", 8),
  mcq("Koji deo Srbije je najgušće naseljen?", ["Beogradska oblast", "Vojvodina", "Južna Srbija", "Istočna Srbija"], "Beogradska oblast", "easy", 8),
  mcq("Koja je najniža tačka Srbije?", ["Ušće Timoka u Dunav", "Beograd", "Nizija kod Subotice", "Vlasinsko jezero"], "Ušće Timoka u Dunav", "hard", 8),
  mcq("Koja planina u Srbiji pripada vencu Dinarskih planina?", ["Zlatar", "Rtanj", "Stara planina", "Suva planina"], "Zlatar", "medium", 8),
  mcq("Kako se zove najveća peščara u Evropi, koja se nalazi u Srbiji?", ["Deliblatska peščara", "Subotička peščara", "Telečka peščara", "Ramska peščara"], "Deliblatska peščara", "easy", 8),
  mcq("Koja reka čini granicu između Srbije i Bosne i Hercegovine?", ["Drina", "Sava", "Morava", "Uvac"], "Drina", "easy", 8),
  mcq("Koja je najduža klisura u Srbiji (i Evropi)?", ["Đerdapska klisura", "Sićevačka klisura", "Grdelička klisura", "Ovčarsko-kablarska klisura"], "Đerdapska klisura", "easy", 8),
  mcq("Koji je najveći ugljeni basen u Srbiji?", ["Kolubarski basen", "Kostolački basen", "Timočki basen", "Senijsko-resavski basen"], "Kolubarski basen", "medium", 8),
  mcq("Koja planina je najviša u Vojvodini?", ["Fruška gora", "Vršačke planine", "Telečka", "Titelski breg"], "Vršačke planine", "medium", 8),
  mcq("Koja reka protiče kroz grad Zaječar?", ["Beli Timok", "Nišava", "Mlava", "Pek"], "Beli Timok", "medium", 8),
  mcq("Koji nacionalni park je poznat po staništu Pančićeve omorike?", ["Tara", "Kopaonik", "Đerdap", "Fruška gora"], "Tara", "easy", 8),
  mcq("Koji grad u Srbiji je poznat po proizvodnji pirotskog ćilima?", ["Pirot", "Vranje", "Leskovac", "Niš"], "Pirot", "easy", 8),
  mcq("Koja je najstarija planina u Srbiji?", ["Jastrebac", "Kopaonik", "Zlatibor", "Tara"], "Jastrebac", "hard", 8),
  mcq("Koji grad u Srbiji nazivaju 'gradom na dve reke' (Dunav i Tamiš)?", ["Pančevo", "Smederevo", "Zrenjanin", "Novi Sad"], "Pančevo", "medium", 8),
  mcq("Koje je najtoplije banjsko lečilište u Srbiji (voda do 96°C)?", ["Vranjska Banja", "Sijarinska Banja", "Jošanička Banja", "Kuršumlijska Banja"], "Vranjska Banja", "hard", 8),
  mcq("Kojoj grupi planina po postanku pripada planina Rtanj?", ["Karpatsko-balkanskim", "Dinarskim", "Gromadnim", "Vulkanskim"], "Karpatsko-balkanskim", "medium", 8),
  mcq("Koja reka protiče kroz grad Čačak?", ["Zapadna Morava", "Ibar", "Gruža", "Moravica"], "Zapadna Morava", "easy", 8),
  mcq("Gde se nalazi čuveni prirodni fenomen 'Đavolja varoš'?", ["Planina Radan", "Planina Golija", "Planina Cer", "Planina Bukulja"], "Planina Radan", "medium", 8),
  mcq("Koja je najveća nizija u centralnoj Srbiji?", ["Pomoravlje", "Mačva", "Stig", "Negotinska nizija"], "Pomoravlje", "medium", 8),
  mcq("Koji kanal povezuje Dunav i Tisu?", ["Kanal Dunav-Tisa-Dunav", "Panamski kanal", "Begejski kanal", "Tamiški kanal"], "Kanal Dunav-Tisa-Dunav", "easy", 8),
  mcq("Koja reka nastaje spajanjem Tare i Pive?", ["Drina", "Lim", "Uvac", "Ćehotina"], "Drina", "hard", 8),
  mcq("Koja je najveća planina po površini u Srbiji?", ["Kopaonik", "Stara planina", "Zlatibor", "Golija"], "Kopaonik", "medium", 8),
  mcq("Koji grad u Srbiji je poznat po festivalu trubača?", ["Guča", "Ivanjica", "Arilje", "Požega"], "Guča", "easy", 8),
  mcq("Koja planina razdvaja Srbiju i Crnu Goru?", ["Prokletije", "Šar-planina", "Zlatar", "Golija"], "Prokletije", "medium", 8),
  dragDrop("Poveži banju sa planinom u čijoj se blizini nalazi.",
    [{ id: "v_banja", label: "Vrnjačka Banja" }, { id: "s_banja", label: "Soko Banja" }, { id: "n_banja", label: "Niška Banja" }],
    [{ id: "goc", label: "Goč" }, { id: "ozren", label: "Ozren" }, { id: "suva_p", label: "Suva planina" }],
    { v_banja: "goc", s_banja: "ozren", n_banja: "suva_p" }, "hard", 8),
  mapClick("Klikni na grad koji je centar Šumadije.", [20.91, 44.01], 12,
    [{ id: "Čačak", coordinates: [20.35, 43.89] }, { id: "Kragujevac", coordinates: [20.91, 44.01] }, { id: "Jagodina", coordinates: [21.26, 43.97] }, { id: "Kraljevo", coordinates: [20.68, 43.72] }],
    "Kragujevac", "hard", 8, 5),
  mapClick("Klikni na područje Đerdapske klisure.", [21.0, 44.50], 7,
    [{ id: "Smederevo", coordinates: [20.92, 44.66] }, { id: "Golubac", coordinates: [21.62, 44.65] }, { id: "Djerdap", coordinates: [22.25, 44.65] }, { id: "Kladovo", coordinates: [22.60, 44.61] }],
    "Djerdap", "hard", 8, 3),
  mapClick("Pronađi na mapi planinu Kopaonik.", [20.5, 43.8], 7,
    [{ id: "Zlatibor", coordinates: [20.20, 43.73] }, { id: "Kopaonik", coordinates: [20.81, 43.28] }, { id: "Tara", coordinates: [19.80, 44.00] }],
    "Kopaonik", "hard", 8, 8),
];

// === EVROPA ===
const evropa = [
  mcq("Glavni grad Francuske je:", ["Pariz", "Rim", "Berlin", "Madrid"], "Pariz", "easy", 6),
  mcq("Glavni grad Italije je:", ["Rim", "Atina", "Lisabon", "Budimpešta"], "Rim", "easy", 6),
  mcq("Glavni grad Nemačke je:", ["Berlin", "Beč", "Prag", "Varšava"], "Berlin", "easy", 6),
  mcq("Glavni grad Grčke je:", ["Atina", "Sofija", "Zagreb", "Podgorica"], "Atina", "easy", 6),
  mcq("Glavni grad Mađarske je:", ["Beč", "Budimpešta", "Prag", "Varšava"], "Budimpešta", "easy", 6),
  mcq("Glavni grad Hrvatske je:", ["Sarajevo", "Ljubljana", "Zagreb", "Podgorica"], "Zagreb", "easy", 6),
  mcq("Glavni grad Bosne i Hercegovine je:", ["Sarajevo", "Mostar", "Tuzla", "Banja Luka"], "Sarajevo", "easy", 6),
  mcq("Glavni grad Crne Gore je:", ["Podgorica", "Nikšić", "Cetinje", "Bar"], "Podgorica", "easy", 6),
  mcq("Glavni grad Severne Makedonije je:", ["Skoplje", "Ohrid", "Bitolj", "Tetovo"], "Skoplje", "easy", 6),
  mcq("Glavni grad Rumunije je:", ["Bukurešt", "Sofija", "Budimpešta", "Beč"], "Bukurešt", "easy", 6),
  mcq("Glavni grad Austrije je:", ["Beč", "Berlin", "Prag", "Bratislava"], "Beč", "easy", 6),
  mcq("Glavni grad Španije je:", ["Madrid", "Lisabon", "Barselona", "Sevilja"], "Madrid", "easy", 6),
  mcq("Glavni grad Portugala je:", ["Lisabon", "Porto", "Madrid", "Braga"], "Lisabon", "easy", 6),
  mcq("Glavni grad Slovenije je:", ["Ljubljana", "Zagreb", "Beč", "Budimpešta"], "Ljubljana", "easy", 6),
  mcq("Glavni grad Velike Britanije je:", ["London", "Dablin", "Edinburg", "Cardiff"], "London", "easy", 6),
  mcq("Glavni grad Češke je:", ["Prag", "Beč", "Varšava", "Bratislava"], "Prag", "easy", 6),
  mcq("Glavni grad Poljske je:", ["Varšava", "Krakov", "Gdanjsk", "Lođ"], "Varšava", "easy", 6),
  mcq("Glavni grad Holandije je:", ["Amsterdam", "Roterdam", "Hag", "Utreht"], "Amsterdam", "easy", 6),
  mcq("Glavni grad Švajcarske je:", ["Bern", "Cirih", "Ženeva", "Lozana"], "Bern", "easy", 6),
  mcq("Koja reka protiče kroz Budimpeštu?", ["Dunav", "Sava", "Tisa", "Morava"], "Dunav", "easy", 6),
  mcq("Glavni grad Bugarske je:", ["Sofija", "Plovdiv", "Varna", "Ruse"], "Sofija", "easy", 6),
  mcq("Glavni grad Slovačke je:", ["Bratislava", "Prag", "Beč", "Budimpešta"], "Bratislava", "easy", 6),
  mcq("Glavni grad Norveške je:", ["Oslo", "Stokholm", "Kopenhagen", "Helsinki"], "Oslo", "easy", 7),
  mcq("Glavni grad Švedske je:", ["Stokholm", "Oslo", "Kopenhagen", "Helsinki"], "Stokholm", "easy", 7),
  mcq("Glavni grad Finske je:", ["Helsinki", "Oslo", "Stokholm", "Rejkjavik"], "Helsinki", "easy", 7),
  mcq("Glavni grad Danske je:", ["Kopenhagen", "Oslo", "Stokholm", "Rejkjavik"], "Kopenhagen", "easy", 7),
  mcq("Glavni grad Irske je:", ["Dablin", "London", "Edinburg", "Belfast"], "Dablin", "easy", 7),
  mcq("Glavni grad Islanda je:", ["Rejkjavik", "Oslo", "Helsinki", "Kopenhagen"], "Rejkjavik", "easy", 7),
  mcq("Najveće poluostrvo u Evropi je:", ["Balkansko poluostrvo", "Apeninsko poluostrvo", "Ibersko poluostrvo", "Skandinavsko poluostrvo"], "Balkansko poluostrvo", "medium", 7),
  mcq("Najduža reka u Evropi je:", ["Volga", "Dunav", "Rajna", "Loara"], "Volga", "medium", 7),
  mcq("Najveće ostrvo u Evropi je:", ["Velika Britanija", "Island", "Sicilija", "Korzika"], "Velika Britanija", "medium", 7),
  mcq("Koji moreuz spaja Atlantski okean i Sredozemno more?", ["Gibraltar", "Bosfor", "Dardaneli", "Lamanš"], "Gibraltar", "medium", 7),
  mcq("Najveća aktivna vulkanska planina u Evropi je:", ["Etna", "Vezuv", "Olimp", "Mon Blan"], "Etna", "medium", 7),
  mcq("Koja država je najveći proizvođač maslina u Evropi?", ["Španija", "Nemačka", "Poljska", "Švedska"], "Španija", "easy", 7),
  mcq("Gde se nalazi sedište Evropske unije?", ["Brisel", "Strazbur", "Luksemburg", "Hag"], "Brisel", "medium", 7),
  mcq("Koji planinski sistem čini prirodnu granicu između Evrope i Azije?", ["Ural", "Kavkaz", "Karpati", "Pirineji"], "Ural", "medium", 7),
  dragDrop("Poveži državu i glavni grad.",
    [{ id: "francuska", label: "Francuska" }, { id: "nemacka", label: "Nemačka" }, { id: "italija", label: "Italija" }, { id: "spanija", label: "Španija" }],
    [{ id: "pariz", label: "Pariz" }, { id: "berlin", label: "Berlin" }, { id: "rim", label: "Rim" }, { id: "madrid", label: "Madrid" }],
    { francuska: "pariz", nemacka: "berlin", italija: "rim", spanija: "madrid" }, "medium", 6),
  mapClick("Klikni Berlin na mapi Evrope.", [10, 50], 3,
    [{ id: "pariz", coordinates: [2.3522, 48.8566] }, { id: "berlin", coordinates: [13.405, 52.52] }, { id: "rim", coordinates: [12.4964, 41.9028] }],
    "berlin", "medium", 6, 8),
  mapClick("Klikni Pariz na mapi Evrope.", [10, 50], 3,
    [{ id: "pariz", coordinates: [2.3522, 48.8566] }, { id: "berlin", coordinates: [13.405, 52.52] }, { id: "rim", coordinates: [12.4964, 41.9028] }],
    "pariz", "medium", 6, 8),
  mapClick("BOSS LEVEL: Klikni na Italiju.", [15, 50], 2.5, [], "Italy", "hard", 7, 0),
  mapClick("BOSS LEVEL: Lociraj Grčku na mapi Evrope.", [15, 50], 2.5, [], "Greece", "hard", 7, 0),
  mapClick("BOSS LEVEL: Klikni na Mađarsku (severni sused Srbije).", [15, 50], 2.5, [], "Hungary", "hard", 8, 0),
  mapClick("BOSS LEVEL: Gde se nalazi Rumunija?", [15, 50], 2.5, [], "Romania", "hard", 8, 0),
  mapClick("BOSS LEVEL: Lociraj Bosnu i Hercegovinu.", [15, 50], 2.5, [], "Bosnia and Herz.", "hard", 8, 0),
  mapClick("BOSS LEVEL: Pronađi Island na mapi.", [0, 0], 1, [], "Iceland", "hard", 7, 0),
];

// === SVET ===
const svet = [
  mcq("Najveći kontinent na svetu je:", ["Azija", "Evropa", "Afrika", "Australija"], "Azija", "easy", 7),
  mcq("Najveći okean na svetu je:", ["Tihi okean", "Atlantski okean", "Indijski okean", "Severni ledeni okean"], "Tihi okean", "medium", 7),
  mcq("Najveća država po površini je:", ["Rusija", "Kanada", "Kina", "SAD"], "Rusija", "medium", 7),
  mcq("Glavni grad Japana je:", ["Tokio", "Osaka", "Peking", "Seul"], "Tokio", "easy", 7),
  mcq("Glavni grad Australije je:", ["Kanbera", "Sidnej", "Melburn", "Pert"], "Kanbera", "easy", 7),
  mcq("Koji kontinent se naziva 'crni kontinent'?", ["Afrika", "Evropa", "Azija", "Južna Amerika"], "Afrika", "easy", 7),
  mcq("Glavni grad SAD je:", ["Vašington", "Njujork", "Čikago", "Los Anđeles"], "Vašington", "easy", 7),
  mcq("Glavni grad Kanade je:", ["Otava", "Toronto", "Vankuver", "Montreal"], "Otava", "easy", 7),
  mcq("Glavni grad Brazila je:", ["Brasília", "Rio de Žaneiro", "Sao Paulo", "Salvador"], "Brasília", "easy", 7),
  mcq("Glavni grad Kine je:", ["Peking", "Šangaj", "Hong Kong", "Tianđin"], "Peking", "easy", 7),
  mcq("Glavni grad Indije je:", ["Nju Delhi", "Mumbaj", "Kalkuta", "Čenaj"], "Nju Delhi", "easy", 7),
  mcq("Glavni grad Egipta je:", ["Kairo", "Luksor", "Aleksandrija", "Asuan"], "Kairo", "easy", 7),
  mcq("Koja je najveća pustinja na svetu?", ["Sahara", "Gobi", "Kalahari", "Atakama"], "Sahara", "medium", 7),
  mcq("Najmanji kontinent je:", ["Australija", "Evropa", "Antarktik", "Južna Amerika"], "Australija", "easy", 7),
  mcq("Glavni grad Meksika je:", ["Meksiko Siti", "Kankun", "Monterej", "Gvadalahara"], "Meksiko Siti", "easy", 7),
  mcq("Glavni grad Argentine je:", ["Buenos Ajres", "Kordoba", "Rosario", "Mendoza"], "Buenos Ajres", "easy", 7),
  mcq("Glavni grad Rusije je:", ["Moskva", "Sankt Peterburg", "Kazan", "Soči"], "Moskva", "easy", 7),
  mcq("Glavni grad Turske je:", ["Ankara", "Istanbul", "Izmir", "Antalija"], "Ankara", "easy", 7),
  mcq("Koji je najduži rečni sistem?", ["Nil", "Amazon", "Jangcekjang", "Mississippi"], "Nil", "medium", 7),
  mcq("Koji kontinent ima najviše država?", ["Afrika", "Evropa", "Azija", "Južna Amerika"], "Afrika", "medium", 7),
  mcq("Najveće ostrvo na svetu je:", ["Grenland", "Madagaskar", "Borneo", "Nova Gvineja"], "Grenland", "medium", 7),
  mcq("Koji okean zapljuskuje zapadnu obalu Afrike?", ["Atlantski okean", "Tihi okean", "Indijski okean", "Arktički okean"], "Atlantski okean", "easy", 7),
  mcq("Koji okean zapljuskuje istočnu obalu Afrike?", ["Indijski okean", "Atlantski okean", "Tihi okean", "Arktički okean"], "Indijski okean", "easy", 7),
  mcq("Koji je glavni grad Saudijske Arabije?", ["Rijad", "Džeda", "Meka", "Medina"], "Rijad", "medium", 8),
  mcq("Koji je glavni grad Južne Koreje?", ["Seul", "Busan", "Inčon", "Daegu"], "Seul", "easy", 8),
  mcq("Najviši planinski vrh na svetu je:", ["Mont Everest", "Kilimandžaro", "Elbrus", "Akonkagva"], "Mont Everest", "medium", 8),
  mcq("Najviša planina u Africi je:", ["Kilimandžaro", "Atlas", "Drakensberg", "Kenija"], "Kilimandžaro", "medium", 8),
  mcq("Glavni grad Novog Zelanda je:", ["Velington", "Auckland", "Krajstčerč", "Dunedin"], "Velington", "medium", 8),
  dragDrop("Poveži državu sa kontinentom.",
    [{ id: "japan", label: "Japan" }, { id: "brazil", label: "Brazil" }, { id: "egipat", label: "Egipat" }, { id: "australija", label: "Australija" }],
    [{ id: "azija", label: "Azija" }, { id: "juzna-amerika", label: "Južna Amerika" }, { id: "afrika", label: "Afrika" }, { id: "australija-zone", label: "Australija" }],
    { japan: "azija", brazil: "juzna-amerika", egipat: "afrika", australija: "australija-zone" }, "medium", 7),
  mapClick("Klikni Tokio na mapi sveta.", [30, 25], 1,
    [{ id: "tokio", coordinates: [139.65, 35.68] }, { id: "kairo", coordinates: [31.24, 30.04] }, { id: "vasington", coordinates: [-77.04, 38.91] }],
    "tokio", "medium", 7, 12),
  mapClick("Klikni Kairo na mapi sveta.", [30, 25], 1,
    [{ id: "tokio", coordinates: [139.65, 35.68] }, { id: "kairo", coordinates: [31.24, 30.04] }, { id: "vasington", coordinates: [-77.04, 38.91] }],
    "kairo", "medium", 7, 12),
  mapClick("BOSS LEVEL: Pronađi Australiju na mapi sveta.", [0, 0], 1, [], "Australia", "hard", 5, 0),
  mapClick("BOSS LEVEL: Klikni na Grenland.", [0, 0], 1, [], "Greenland", "hard", 5, 0),
  mapClick("BOSS LEVEL: Gde se nalazi Brazil?", [0, 0], 1, [], "Brazil", "hard", 6, 0),
  mapClick("BOSS LEVEL: Lociraj Indiju na mapi Azije.", [0, 0], 1, [], "India", "hard", 6, 0),
];

// === PRIRODA I DRUŠTVO ===
const priroda = [
  mcq("Koji uređaj pokazuje strane sveta?", ["Kompas", "Termometar", "Higrometar", "Barometar"], "Kompas", "easy", 5),
  mcq("Koja strana sveta je suprotna severu?", ["Jug", "Istok", "Zapad", "Severoistok"], "Jug", "easy", 5),
  mcq("Koja strana sveta je obično na vrhu karte?", ["Sever", "Jug", "Istok", "Zapad"], "Sever", "easy", 5),
  mcq("Koja strana sveta je tamo gde Sunce izlazi?", ["Istok", "Zapad", "Sever", "Jug"], "Istok", "easy", 5),
  mcq("Koja strana sveta je tamo gde Sunce zalazi?", ["Zapad", "Istok", "Sever", "Jug"], "Zapad", "easy", 5),
  mcq("Kako se zove mesto odakle reka izvire?", ["Izvor", "Ušće", "Obala", "Tok"], "Izvor", "easy", 5),
  mcq("Kako se zove mesto gde se reka uliva u more ili drugu reku?", ["Ušće", "Izvor", "Brana", "Kanal"], "Ušće", "medium", 5),
  mcq("Koji oblik reljefa je uzvišenje sa strmim stranama?", ["Planina", "Ravnica", "Nizija", "Obala"], "Planina", "easy", 5),
  mcq("Koji oblik reljefa je široko i ravno zemljište?", ["Ravnica", "Planina", "Klanac", "Litica"], "Ravnica", "easy", 5),
  mcq("Šta je globus?", ["Model Zemlje", "Vrsta karte", "Planina", "Reka"], "Model Zemlje", "easy", 5),
  mcq("Šta je mapa?", ["Prikaz Zemljine površine u ravni", "Merna traka", "Vrsta planine", "Vrsta reke"], "Prikaz Zemljine površine u ravni", "medium", 5),
  mcq("Šta pokazuje merilo na karti?", ["Odnos na karti i u stvarnosti", "Boju karte", "Broj država", "Naziv planine"], "Odnos na karti i u stvarnosti", "medium", 5),
  mcq("Koja karta prikazuje granice država?", ["Politička karta", "Fizička karta", "Topografska karta", "Morska karta"], "Politička karta", "easy", 5),
  mcq("Koja karta prikazuje reljef i vode?", ["Fizička karta", "Politička karta", "Saobraćajna karta", "Turistička karta"], "Fizička karta", "easy", 5),
  mcq("Koje je kopno sa svih strana okruženo vodom?", ["Ostrvo", "Poluostrvo", "Kontinent", "Ravnica"], "Ostrvo", "easy", 5),
  mcq("Koji deo kopna je okružen vodom sa tri strane?", ["Poluostrvo", "Ostrvo", "Planina", "Nizija"], "Poluostrvo", "easy", 5),
  mcq("Šta je more?", ["Velika slana vodena površina", "Reka", "Jezero", "Izvor"], "Velika slana vodena površina", "easy", 5),
  mcq("Šta je jezero?", ["Stajaća voda okružena kopnom", "Tekuća voda", "Planinski vrh", "Vrsta ostrva"], "Stajaća voda okružena kopnom", "easy", 5),
  mcq("Šta je klima?", ["Prosečno vreme tokom dužeg perioda", "Vetar u jednom danu", "Oblik reke", "Vrsta karte"], "Prosečno vreme tokom dužeg perioda", "medium", 5),
  mcq("Šta je dolina?", ["Ulegnuće između uzvišenja", "Vrsta mora", "Vrsta ostrva", "Planinski vrh"], "Ulegnuće između uzvišenja", "easy", 5),
  mcq("Šta je pritoka?", ["Reka koja se uliva u drugu reku", "Mesto gde reka izvire", "Morski zaliv", "Planina pored reke"], "Reka koja se uliva u drugu reku", "medium", 5),
  mcq("Šta je reljef?", ["Oblik Zemljine površine", "Vrsta klime", "Vrsta mora", "Vrsta karte"], "Oblik Zemljine površine", "easy", 5),
  mcq("Šta je obala?", ["Deo kopna uz vodu", "Deo planine", "Deo reke", "Deo karte"], "Deo kopna uz vodu", "easy", 5),
  mcq("Koja strana sveta je između severa i istoka?", ["Severoistok", "Severozapad", "Jugoistok", "Jugozapad"], "Severoistok", "medium", 5),
  mcq("Koja strana sveta je između juga i zapada?", ["Jugozapad", "Severoistok", "Severozapad", "Jugoistok"], "Jugozapad", "medium", 5),
  mcq("Koji instrument meri temperaturu?", ["Termometar", "Kompas", "Pluviometar", "Barometar"], "Termometar", "easy", 5),
  mcq("Koji instrument meri količinu padavina?", ["Pluviometar", "Termometar", "Kompas", "Ravnalo"], "Pluviometar", "medium", 5),
  mcq("Kako se zove uska i duboka uvala između strmih stena?", ["Klisura", "Nizija", "Ravnica", "Laguna"], "Klisura", "medium", 5),
  mcq("Koji instrument meri atmosferski pritisak?", ["Barometar", "Termometar", "Kompas", "Pluviometar"], "Barometar", "easy", 5),
  mcq("Koliko kontinenata postoji na Zemlji?", ["5", "6", "7", "8"], "7", "easy", 5),
  mcq("Koja linija deli Zemlju na severnu i južnu poluloptu?", ["Ekvator", "Grinič", "Povratnik", "Polarnik"], "Ekvator", "easy", 5),
  mcq("Zemlja se okreće oko svoje ose. To kretanje se zove:", ["Rotacija", "Revolucija", "Evolucija", "Orbita"], "Rotacija", "easy", 5),
  mcq("Koliko traje jedna revolucija Zemlje?", ["24 sata", "Mesec dana", "365 dana", "100 godina"], "365 dana", "easy", 5),
  mcq("Koji je najveći okean na svetu?", ["Tihi", "Atlantski", "Indijski", "Severni ledeni"], "Tihi", "easy", 5),
  mcq("Koja država zauzima najveći deo Južne Amerike?", ["Brazil", "Argentina", "Čile", "Peru"], "Brazil", "medium", 5),
  mcq("Koja reka je najduža u Africi?", ["Nil", "Kongo", "Niger", "Zambezi"], "Nil", "easy", 6),
  mcq("Koji planinski venac se pruža duž zapadne obale Južne Amerike?", ["Andi", "Himalaji", "Kordiljeri", "Alpi"], "Andi", "medium", 6),
  mcq("Koja pustinja je najveća u Aziji?", ["Gobi", "Sahara", "Kalahari", "Atakama"], "Gobi", "medium", 6),
  mcq("Kako se zove najviši vrh na svetu?", ["Mont Everest", "K2", "Mon Blan", "Akonkagva"], "Mont Everest", "easy", 6),
  mcq("Koji kanal spaja Atlantski i Tihi okean?", ["Panamski kanal", "Suecki kanal", "Korintski kanal", "Kielski kanal"], "Panamski kanal", "medium", 6),
  mcq("Koja država je najmnogoljudnija na svetu?", ["Indija", "Kina", "SAD", "Rusija"], "Indija", "easy", 6),
  mcq("Koja reka ima najveći protok vode na svetu?", ["Amazon", "Nil", "Dunav", "Misisipi"], "Amazon", "medium", 6),
  mcq("Pronađi ostrvo na jugoistoku Afrike poznato po specifičnom životinjskom svetu.", ["Madagaskar", "Grenland", "Sicilija", "Krit"], "Madagaskar", "medium", 5),
  dragDrop("Poveži instrument sa onim što meri.",
    [{ id: "kompas", label: "Kompas" }, { id: "termometar", label: "Termometar" }, { id: "pluviometar", label: "Pluviometar" }, { id: "barometar", label: "Barometar" }],
    [{ id: "strane-sveta", label: "Strane sveta" }, { id: "temperatura", label: "Temperatura" }, { id: "padavine", label: "Padavine" }, { id: "pritisak", label: "Atmosferski pritisak" }],
    { kompas: "strane-sveta", termometar: "temperatura", pluviometar: "padavine", barometar: "pritisak" }, "medium", 5),
  dragDrop("Poveži državu sa njenim kontinentom.",
    [{ id: "egipat", label: "Egipat" }, { id: "kina", label: "Kina" }, { id: "peru", label: "Peru" }],
    [{ id: "afrika", label: "Afrika" }, { id: "azija", label: "Azija" }, { id: "j_amerika", label: "Južna Amerika" }],
    { egipat: "afrika", kina: "azija", peru: "j_amerika" }, "medium", 6),
];

// === SPAJANJE ===
const questions = [
  ...srbija.map(q => ({ ...q, category: "Srbija" })),
  ...evropa.map(q => ({ ...q, category: "Evropa" })),
  ...svet.map(q => ({ ...q, category: "Svet" })),
  ...priroda.map(q => ({ ...q, category: "Priroda i društvo" })),
];

// === SEED ===
async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Brisanje starih pitanja...");
    await Question.deleteMany({});
    await Question.insertMany(questions);
    console.log(`✅ Seeded ${questions.length} questions successfully.`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error);
    process.exit(1);
  }
}

seed();